### PR TITLE
Fix potential SEGFAULT on concurrent nested filter and hash bucket compaction

### LINKED ISSUE #2211: Bug: SEGFAULT when running specific filters
Originally discovered by @ju-bezdek. (Thank you!) 

## How to reproduce:
- Provoke a compaction of properpty hash buckets. (_This is not too trivial unless you know exactly what leads to a compaction in this bucket._)
- Run plenty of nested filtered vector searches that would be eligible for caching. 

## Expected Behavior
No crashes

## Actual Behavior
Sooner or later something like this should occur:

image

### PR DESCRIPTION
**Pull request by etiennedi**
### What's being changed:
- There was essentially a data race between the property hash buckets and compactions happening on those buckets. The values are obtained using an `inverted.RowReader` which wraps a Cursor. The values are only threadsafe until the cursor is closed. In our scenario we are using the values also after the work done through the`RowReader` has been completed. This is now threadsafe by copying the hash instead of referencing it. This behavior is covered by a [completely new chaos pipeline](https://github.com/semi-technologies/weaviate-chaos-engineering/pull/11).
- This PR also adds the ability to override the idle memtable flush threshold (default=60s), as the new chaos pipeline forces a flush by waiting. Without this feature, the pipeline would have to wait for 10x60s, now it waits for just 10x5s. A unit test for parsing the config was added.

Fixes #2211 

### Review checklist

- ~~Documentation has been updated, if necessary. Link to changed documentation:~~
- [x] Chaos pipeline run or not necessary. Link to pipeline: see below
- [x] All new code is covered by tests where it is reasonable: new config has unit test, racy behavior [has new chaos pipeline](https://github.com/semi-technologies/weaviate-chaos-engineering/pull/11) scenario (which is now green).
- ~~Performance tests have been run or not necessary.~~ deemed not necessary

### CODE REVIEW

**Comment by etiennedi** [comment]
[Failing Chaos Pipeline before the fix](https://app.travis-ci.com/github/semi-technologies/weaviate-chaos-engineering/jobs/583113035)

**Comment by etiennedi** [comment]
[The chaos pipeline is green after the fix](https://app.travis-ci.com/github/semi-technologies/weaviate-chaos-engineering/builds/255684722) - including the new pipeline.

image

**Review by dirkkul — APPROVED** [review]

File: adapters/repos/db/inverted/searcher_doc_pointers.go [hunk 1]
```diff
@@ -75,7 +75,16 @@ func (fs *Searcher) docPointersInvertedNoFrequency(prop string, b *lsmkv.Bucket,
...
 		}
 
-		hashes = append(hashes, currHash)
+		// currHash is only safe to access for the lifetime of the RowReader, once
+		// that has finished, a compaction could happen and remove the underlying
+		// memory that the slice points to. Since the hashes will be used to merge
+		// filters - which happens after the RowReader has completed - this can lead
+		// to segfault crashes. Now is the time to safely copy it, creating a new
+		// and immutable slice.
+		hashCopy := make([]byte, len(currHash))
```
Comment (redouan-rhazouani) [inline adapters/repos/db/inverted/searcher_doc_pointers.go:84]: To avoid repetition and to encourage reuse I would define a small function

```
func copyBytes(bs []byte) []byte {
	new := make([]byte, len(bs))
	copy(new, bs)
	return new
}
```
We would end up with line below which is shorter and more expressive at same time
`hashes = append(hashes, copyBytes(currHash))`

Comment (etiennedi) [reply adapters/repos/db/inverted/searcher_doc_pointers.go:84]: Good point, I'll add it.

**Review by antas-marcin — APPROVED** [review]

**Review by redouan-rhazouani — APPROVED** [review]

File: adapters/repos/db/inverted/searcher_doc_pointers.go (hunk 1 above)
Comment (etiennedi) [reply adapters/repos/db/inverted/searcher_doc_pointers.go]: Done
