### PR TITLE
Fix create/update timestamp issues in GraphQL and REST

### LINKED ISSUE #1809: (404) Link to OpenAI new module documentation is broken
Hi,

https://www.semi.technology/developers/weaviate/current/modules/text2vec-openai.md does not exist

### PR DESCRIPTION
**Pull request by parkerduckworth**
### Changes

1.  Set the original creation timestamp before call to put, otherwise it is lost. This is because `class` is unmarshaled directly from the request body, therefore `CreationTimeUnix` inherits the zero value.

2. Add `creationTimeUnix` and `lastUpdateTimeUnix` fields to `Get` graphql query as `String`'s

3. Write tests to assert both `1.` and `2.`
 
---

Fixes #1809

### CODE REVIEW

File: usecases/objects/update.go [hunk 1]
```diff
@@ -62,6 +62,11 @@ func (m *Manager) updateObjectToConnectorAndSchema(ctx context.Context, principa
 		return nil, NewErrInvalidUserInput("invalid object: %v", err)
 	}
 
+	// Set the original creation timestamp before call to put,
+	// otherwise it is lost. This is because `class` is unmarshaled
+	// directly from the request body, therefore `CreationTimeUnix`
+	// inherits the zero value.
+	class.CreationTimeUnix = originalObject.Created
```
Comment (etiennedi) [inline usecases/objects/update.go:69]: Love this comment. The perfect level of information about why we do this.

**Comment by parkerduckworth** [comment]
Just pushed some some tests to `traverser/exporer_test.go` as I just realized I hadn't covered the code added to that package.
