### PR TITLE
Fix total of 6 bugs related to indexing into LSM Store and HNSW index

### LINKED ISSUE #2190: Potential Bug in LSMKV memtable when updating secondary key of existing entry
It seems the entry can still be retrieved by the old key. This could for example lead to the HNSW index degrading over time as it was potentially reading stale data that it should have no longer had access to. In extreme cases, it could lead to weird errors such as 
```
calculate distance between candidate and query: vector lengths don't match: 128 vs 0
```

when removing the vector from an object through `PUT`, and then inserting again.

### LINKED ISSUE #2193: Bug: PATCH Merge can break inverted index
If there a PATCH merge occurs it may break some unaffected fields, such as `[]date`, and `date`.

### LINKED ISSUE #2194: Bug: Concurrent Index and Delete can mess up HNSW insert operations
It seems this bug is not new, but it was hidden by the behavior described in #2190. Once a fix is in there - this becomes obvious.

### LINKED ISSUE #2195: Bug: PATCH Merge does not update geoCoordinates index
Discovered as part of #2193, while put and batch put correctly update property-specific indices, such as the geo-coordinates.

### LINKED ISSUE #2197: Bug: potential index-out-of-range panic in delete cleanup
It seems this bug was either created by one of the fixes as part of #2191 or - more likely - it had already existed, but was hidden:

```
panic: runtime error: index out of range [7] with length 7

goroutine 4788959 [running]:
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).searchLayerByVector(0x140063f96c0, {0x14004028680, 0x20, 0x20}, 0x5000?, 0x40, 0x7, 0x0)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/search.go:204 +0xa58
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).doAtLevel(0x1400084d9b8, 0x9?)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:80 +0xc4
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).Do(0x1400084d9b8)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:62 +0x4c
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findAndConnectNeighbors(0x140063f96c0?, 0x1400084db68?, 0x7?, {0x14004028680?, 0x14004028680?, 0x20?}, 0x20?, 0x100edfadc?, 0x14000aeca60?)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:30 +0x5c
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x140063f96c0, 0x477b, 0x140034a6ff0?, 0x0?)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:340 +0x944
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf(0x140063f96c0, 0x100edeacc?, 0x10154cdac?)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:249 +0x12c
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).CleanUpTombstonedNodes(0x140063f96c0, 0x140072f2f60)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:190 +0x194
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).tombstoneCleanup(0x140063f96c0, 0x14009eae2a0?)
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:127 +0x28
github.com/semi-technologies/weaviate/entities/cyclemanager.(*CycleManager).Start.func1()
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/entities/cyclemanager/cyclemanager.go:72 +0x138
created by github.com/semi-technologies/weaviate/entities/cyclemanager.(*CycleManager).Start
        /Users/etiennedilocker/code/github.com/semi-technologies/weaviate/entities/cyclemanager/cyclemanager.go:56 +0xc8
exit status 2
```

### LINKED ISSUE #2198: Bug: "entrypoint deleted, will be cleaned up in next cycle"
Whether this was a bug or not is debatable, but it was annoying. As the deep investigation for #2191 showed, this should be improved.

image

### PR DESCRIPTION
**Pull request by etiennedi**
This PR fixes the following bugs in chronological order of discovery:

* ### Fix an issue where LSM memtable returned values for since-changed secondary keys
  This was discovered as part of another investigation. It was impossible to add vectors if there were objects that previously had a vector, but it got remove through an update. The vector index would fail with "distance calculation: 0 vs 128". Because of the memtable issue, it was possible to partially retrieve an object that no longer existed, thus leading to `nil` vectors. Fixes #2190. New tests were added to the memtable itself that reproduced the problem before and are now green.

* ### Fix issue where PATCH could break some props
  This issue popped up after fixing #2190, because it was hidden by the broken behavior. If PATCH updated some props, but left overs untouched, the untouched props could be messed up in the inverted index, thus leading to failed searches afterwards. This was due to incorrect type assertions in combination with broken error handling in the `inverted` package.   Fixes #2193. A new elaborate test was added that makes uses of both untouched and touched props and makes sure the object is retrievable through each of them.

* ### Fix issue where concurrent HNSW. insert and delete operations led to issues
  With #2190 fixed this showed up. The fix is relatively simple: There is a new lock that prevents concurrent indexing and deleting. This is the biggest performance risk in this PR. Luckily it has no negative impact – as can be seen by the performance test runs below. Fixes #2194. No new tests were added as the existing test suite already showed this issue with the other issues fixed.
  
* ### Fix issue where PATCH would not update geoProps
  This was a purely serendipitous find. As part of the new tests to prove that #2193 is fixed, also geo props were added. This showed that while there was not an update with untouched props, the whole update operation was never reflected. Fixes #2195. The test as part of #2193 is only green with this fix in, no separate test was deemed necessary.

* ### Fix "entry point deleted - will be cleaned up in next cycle"
  This showed up in the chaos pipeline because of the fixes in #2190 which now makes it much more likely to run into an entry point that no longer exists and needs to be updated. The existing logic to replace entry points was a bit hard to read and not very robust. It was spread out over too many places and just made one attempt to replace the EP. If the replacement was then also deleted in the object store before a distance to it could be calculated, the user would see the above error. The new logic is much cleaner, there is a single `pickEntrypoint()` method that is called from only a single place. Within the method, there are two noteable changes: 1. it takes all criteria into account, making it impossible for the logic to find an alternative and that alternative to then fail in the next step. 2. it makes more than a single attempt, it runs in a loop until it finds an alternative. A new context is spawned to make this logic fail after 60s. It is highly unlikely that the logic would ever spend this much time in there, but I wanted some sort of a circuit breaker in case the underlying object store was buggy or super slow to prevent the cascading blocking and getting stuck in this loop forever. Fixes #2198. A new test was added that reproduced the issue in one case. Other cases were reproduced by the chaos pipeline.

* ### Fix potential out-of-range panics in HNSW delete logic
  For this one, I'm not 100% sure where this comes from. My suspicion is that this bug was introduced by #2146, but it was super unlikely to occur because #2190 hid the need for cases where the entry point was properly replaced in the delete cleanup. This was fixed by making the connection logic a bit more robust. If level expectations weren't met, the object is adapted correctly. Fixes #2197. This is the only one of the fixes that have no explicit test in Weaviate as the chaos pipeline clearly reproduced this issue with all the other issues fixed. It's not 100% ideal to only rely on the chaos pipeline because of the late feedback, but I couldn't think of a "good" way to write a test for this that doesn't run for ages, and also this PR that was supposed to be 50 lines, has grown substantially because of all the other bugs that were discovered and fixed.

### Review checklist

- [ ] ~~Documentation has been updated, if necessary. Link to changed documentation:~~ only fixes
- [x] Chaos pipeline run or not necessary. Link to pipeline: See comment below
- [x] All new code is covered by tests where it is reasonable. Various new tests, see description above
- [x] Performance tests have been run or not necessary: See comment below

### CODE REVIEW

**Comment by etiennedi** [comment]
This is almost ready, but there is one thing that still needs to be addressed. Under heavy update load we are still occasionally getting this error:

image

I think the current "replace entrypoint" logic needs to improved. Right now it fails on the first ep that is deleted, but it could just keep going and look for a better one.

**Comment by etiennedi** [comment]
Performance is identical.

image

**Comment by etiennedi** [comment]
Managed to get all tests passing and the [chaos pipeline is green](https://app.travis-ci.com/github/semi-technologies/weaviate-chaos-engineering/builds/255416363) for the first time.

image

**Review by aliszka — APPROVED** [review]

File: adapters/repos/db/inverted/objects.go [hunk 1]
```diff
@@ -473,3 +507,43 @@ func (a *Analyzer) analyzeRefProp(prop *models.Property,
...
+		out := make([]interface{}, len(typed))
+		for i := range out {
+			out[i] = typed[i]
+		}
+		return out, nil
+	case []int:
+		out := make([]interface{}, len(typed))
+		for i := range out {
+			out[i] = typed[i]
+		}
```
Comment (dirkkul) [inline adapters/repos/db/inverted/objects.go:526]: test?

File: adapters/repos/db/inverted/objects.go [hunk 2]
```diff
@@ -473,3 +507,43 @@ func (a *Analyzer) analyzeRefProp(prop *models.Property,
...
+		return out, nil
+	case []bool:
+		out := make([]interface{}, len(typed))
+		for i := range out {
+			out[i] = typed[i]
+		}
```
Comment (dirkkul) [inline adapters/repos/db/inverted/objects.go:538]: also test please :)

File: adapters/repos/db/lsmkv/memtable_test.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+func Test_MemtableSecondaryKeyBug(t *testing.T) {
+	dir := t.TempDir()
+	m, err := newMemtable(path.Join(dir, "will-never-flush"), StrategyReplace, 1, nil)
+	require.Nil(t, err)
+
+	t.Run("add initial value", func(t *testing.T) {
+		err = m.put([]byte("my-key"), []byte("my-value"),
+			WithSecondaryKey(0, []byte("secondary-key-initial")))
+		require.Nil(t, err)
+	})
```
Comment (dirkkul) [inline adapters/repos/db/lsmkv/memtable_test.go:22]: Why is adding a value as extra test?

File: adapters/repos/db/vector/hnsw/delete.go [hunk 4]
```diff
@@ -27,6 +27,9 @@ type breakCleanUpTombstonedNodesFunc func() bool
 // Delete attaches a tombstone to an item so it can be periodically cleaned up
 // later and the edges reassigned
 func (h *hnsw) Delete(id uint64) error {
+	h.deleteVsInsertLock.Lock()
+	defer h.deleteVsInsertLock.Unlock()
```
Comment (dirkkul) [inline adapters/repos/db/vector/hnsw/delete.go:31]: maybe add a comment about the lock strategy?

**Review by redouan-rhazouani — APPROVED** [review]

File: adapters/repos/db/vector/hnsw/neighbor_connections.go [hunk 5]
```diff
@@ -188,6 +141,10 @@ func (n *neighborFinderConnector) connectNeighborAtLevel(neighborID uint64,
 
 	neighbor.Lock()
 	defer neighbor.Unlock()
+	if level > neighbor.level {
+		// upgrade neighbor level if the level is out of sync due to a delete re-assign
+		neighbor.upgradeToLevelNoLock(level)
+	}
```
Comment (dirkkul) [inline adapters/repos/db/vector/hnsw/neighbor_connections.go:147]: Also not tested (I'll stop now, but could you go through the changeset and add tests for the non-error pathways?

Comment (etiennedi) [reply adapters/repos/db/vector/hnsw/neighbor_connections.go:147]: For the other cases above (marshalling in between types, etc.) it should be easy to add tests, I can add those. For this one the reason I don't have any is in the PR description:

> This is the only one of the fixes that have no explicit test in Weaviate as the chaos pipeline clearly reproduced this issue with all the other issues fixed. It's not 100% ideal to only rely on the chaos pipeline because of the late feedback, but I couldn't think of a "good" way to write a test for this that doesn't run for ages, and also this PR that was supposed to be 50 lines, has grown substantially because of all the other bugs that were discovered and fixed.

File: adapters/repos/db/vector/hnsw/delete.go (hunk 4 above)
Comment (etiennedi) [reply adapters/repos/db/vector/hnsw/delete.go:31]: Great idea!

File: adapters/repos/db/lsmkv/memtable_test.go (hunk 3 above)
Comment (etiennedi) [reply adapters/repos/db/lsmkv/memtable_test.go:22]: The idea was to have the blocks as small as possible so that reading the title reads like a description of going on. I could also merge this with the next block. WDYT?

File: adapters/repos/db/inverted/objects.go (hunk 1 above)
Comment (etiennedi) [reply adapters/repos/db/inverted/objects.go:526]: The fact this is uncovered makes me wonder if we can ever land in this code path. I'll try to find out more and either remove it or add an explicit test for it. My gut feeling is that this may be required for auto-schema... (maybe @antas-marcin knows more?)

File: adapters/repos/db/lsmkv/memtable_test.go (hunk 3 above)
Comment (dirkkul) [reply adapters/repos/db/lsmkv/memtable_test.go:22]: I would remove the t.run() around it, there is not really anything tested or?

My main annoyence with this is that when the 5th test fails, I cannot run just the 5th test, but I need to run first the "add test" and then the 5th test (or the whole class). I think if all "setup" operations are part of the class itself, they are automatically run in case I just run one test on its own.

File: adapters/repos/db/vector/hnsw/neighbor_connections.go (hunk 5 above)
Comment (dirkkul) [reply adapters/repos/db/vector/hnsw/neighbor_connections.go:147]: alright!

File: adapters/repos/db/inverted/objects.go [hunk 6]
```diff
@@ -473,3 +507,43 @@ func (a *Analyzer) analyzeRefProp(prop *models.Property,
...
+		return out, nil
+	case []float64:
+		out := make([]interface{}, len(typed))
+		for i := range out {
+			out[i] = typed[i]
+		}
+		return out, nil
```
[the remark this answers is not in the document]
Comment (parkerduckworth) [reply adapters/repos/db/inverted/objects.go:545]: This could actually be simplified with generics:

```go
func convertToUntyped[T comparable](in []T) []interface{} {
	out := make([]interface{}, len(in))
	for i := range out {
		out[i] = in[i]
	}
	return out
}

func typedSliceToUntyped2(in any) ([]any, error) {
	switch typed := in.(type) {
	case []any:
		// nothing to do
		return typed, nil
	case []string:
		return convertToUntyped[string](typed), nil
	case []int:
		return convertToUntyped[int](typed), nil
	case []time.Time:
		return convertToUntyped[time.Time](typed), nil
	case []bool:
		return convertToUntyped[bool](typed), nil
	case []float64:
		return convertToUntyped[float64](typed), nil
	default:
		return nil, errors.Errorf("unrecognized slice type %T", in)
	}
}
```

File: adapters/repos/db/inverted/objects.go [hunk 7]
```diff
@@ -346,6 +368,11 @@ func (a *Analyzer) analyzePrimitiveProp(prop *models.Property, value interface{}
 			value = int64(asFloat)
 		}
 
+		if asFloat, ok := value.(int); ok {
```
[the remark this answers is not in the document]
Comment (parkerduckworth) [reply adapters/repos/db/inverted/objects.go]: Fixed

File: adapters/repos/db/merge_integration_test.go [hunk 8]
```diff
@@ -371,3 +374,291 @@ func Test_MergingObjects(t *testing.T) {
...
 }
+
+// This prevents a regression on
+// https://github.com/semi-technologies/weaviate/issues/2193
+//
+// Prior to the fix it was possible that a prop that was not touched during the
+// merge (and therefore only loaded from disk) failed during the
+// inverted-indexing for the new doc id. This was then hidden by the fact that
+// error handling was broken inside the inverted.Analyzer. This test tries to
+// make sure that every possible property type stays in tact if untouched
```
[the remark this answers is not in the document]
Comment (parkerduckworth) [reply adapters/repos/db/merge_integration_test.go]: Fixed

File: adapters/repos/db/inverted/objects.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (parkerduckworth) [reply adapters/repos/db/inverted/objects.go]: I have applied these changes, but with `interface{}` instead of `any` to keep it consistent with the codebase for now

File: adapters/repos/db/inverted/objects.go (hunk 2 above)
Comment (parkerduckworth) [reply adapters/repos/db/inverted/objects.go]: This is covered now

File: adapters/repos/db/inverted/objects.go (hunk 1 above)
Comment (parkerduckworth) [reply adapters/repos/db/inverted/objects.go]: This is covered now

**Review by parkerduckworth — APPROVED** [review]

File: adapters/repos/db/lsmkv/memtable_test.go (hunk 3 above)
Comment (etiennedi) [reply adapters/repos/db/lsmkv/memtable_test.go:22]: In this particular test suite you would need to run them all together anyway because each step does a specific modification to the state and then the next step would assert based on previous state. It's basically one big tests that is only split up into `t.run()`s for better readability.

File: adapters/repos/db/inverted/objects.go [hunk 9]
```diff
@@ -514,36 +514,24 @@ func typedSliceToUntyped(in interface{}) ([]interface{}, error) {
...
-		}
-		return out, nil
+		return convertToUntyped[float64](typed), nil
 	default:
-		return nil, errors.Errorf("unrecognized slice type %T", in)
+		return nil, errors.Errorf("unsupported type %T", in)
+	}
+}
+
+func convertToUntyped[T comparable](in []T) []interface{} {
```
Comment (etiennedi) [inline adapters/repos/db/inverted/objects.go:531]: Love the use of generics here, thanks for this addition! 😍

File: adapters/repos/db/vector/hnsw/delete.go (hunk 4 above)
Comment (etiennedi) [reply adapters/repos/db/vector/hnsw/delete.go:31]: Explanation added [here](https://github.com/semi-technologies/weaviate/pull/2191/commits/d271455415b95a5f5e95398e6b3859e9d0fd8fc1).
